### ISSUE TITLE
compilation error with less 2.0.0

### ISSUE THREAD

**Issue by ysagon** [phiamo/MopaBootstrapBundle#975]
I'm using MopaBootstrapBundle dev-master (3.x with symfony 2.5.x).
I'm using node 0.10.33 (I have tried with version 0.10.25 as well) to compile the less files.

when doing 
```app/console --env=prod assetic:dump```
I get an error:
```
[Assetic\Exception\FilterException]                                                                                                                
  An error occurred while running:                                                                                                                   
  '/usr/bin/node' '/tmp/assetic_lessUHwHnK'                                                                                                          
  Error Output:                                                                                                                                      
  /usr/local/lib/node_modules/less/lib/less/parser/parser.js:108                                                                                     
              imports.contents[fileInfo.filename] = str;                                                                                             
                     ^                                                                                                                               
  TypeError: Cannot read property 'contents' of undefined                                                                                            
      at Object.Parser.parse (/usr/local/lib/node_modules/less/lib/less/parser/parser.js:108:20)                                                     
      at Object.<anonymous> (/tmp/assetic_lessUHwHnK:4:178)                                                                                          
      at Module._compile (module.js:456:26)                                                                                                          
      at Object.Module._extensions..js (module.js:474:10)                                                                                            
      at Module.load (module.js:356:32)                                                                                                              
      at Function.Module._load (module.js:312:12)                                                                                                    
      at Function.Module.runMain (module.js:497:10)                                                                                                  
      at startup (node.js:119:16)                                                                                                                    
      at node.js:902:3                                                                                                                               
  Input:                                                                                                                                             
  /*!                                                                                                                                                
   * MopaBootstrapBundle                                                                                                                             
   *                                                                                                                                                 
   * Copyright 2011 Mohrenweiser & Partner                                                                                                           
   * Licensed under the Apache License v2.0                                                                                                          
   * http://www.apache.org/licenses/LICENSE-2.0                                                                                                      
   *                                                                                                                                                 
   * Import this file in your less files as first to be abled to access less vars from your file                                                     
   * OR                                                                                                                                              
   * Add it to the stylesheets of assetic or                                                                                                         
   * Add it as described on http://www.lesscss.org with the less.js (maybe pathes must be adapted in that case)                                      
   *                                                                                                                                                 
   * Be careful when using less this way, might be most straight forward, but assetic doesnt check the included files                                
   * for changes, and will only regenerate the css if it detects changes in this file!                                                               
   *                                                                                                                                                 
   * For development it might be easier to include all you less files in the layout directly                                                         
   * But then assetic will compile each less file in a own compiler session so you cant mix in the less style into bootstrap, which might not be OK  
   */                                                                                                                                                
  // Main bootstrap.less entry point                                                                                                             
  @import "../bootstrap/less/bootstrap.less";                                                                                                        
  // variables                                                                                                                                       
  @icon-font-path: "/fonts/";                                                                                                                        
  // The Paginator less for MopaBootstrapBundle                                                                                                      
  @import "paginator.less";                                                                                                                          
  // The Subnav less for MopaBootstrapBundle                                                                                                         
  @import "subnav.less";                                                                                                                             
  // Collection support for MopaBootstrapBundle                                                                                                      
  @import "collections.less";                                                                                                                        
  // google Maps support for MopaBootstrapBundle                                                                                                     
  @import "google-maps.less";                                                                                                                        
  // if you have any variables.less file INCLUDE IT AFTER EVERYTHING cause responsive.less also overrides it with the one from bootstrap!!!!!
```
An idea? Thanks

**Comment by phiamo** [comment]
so at least we cant do a lot about that :(
